# Example GitHub Actions workflow for running BYOB benchmarks
# Copy this to .github/workflows/eval.yml in your project

name: Evaluate Model
on:
  workflow_dispatch:
    inputs:
      model_url:
        description: 'Model endpoint URL'
        required: true
      model_id:
        description: 'Model identifier'
        required: true

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install NeMo Evaluator
        run: pip install nemo-evaluator

      - name: Compile benchmark
        run: nemo-evaluator-byob benchmarks/my_benchmark.py

      - name: Run evaluation
        env:
          PYTHONPATH: ~/.nemo-evaluator/byob_packages:$PYTHONPATH
        run: |
          nemo-evaluator run_eval \
            --eval_type byob_my_benchmark.my-benchmark \
            --model_url ${{ inputs.model_url }} \
            --model_id ${{ inputs.model_id }}

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: eval-results
          path: output/
