# Makefile targets for NeMo Evaluator documentation and tooling.

.PHONY: docs-autogen docs-help container-metadata-verify container-metadata-update update-configs

# Absolute repository root (directory containing this makefile).
REPO_ROOT := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))

# Container metadata controller inputs (repo-relative)
MAPPING_TOML ?= $(REPO_ROOT)/packages/nemo-evaluator-launcher/src/nemo_evaluator_launcher/resources/mapping.toml
ALL_TASKS_IRS ?= $(REPO_ROOT)/packages/nemo-evaluator-launcher/src/nemo_evaluator_launcher/resources/all_tasks_irs.yaml
README_FILE ?= $(REPO_ROOT)/README.md

DOCS_DIR = docs

docs-autogen:
	@echo "Regenerating autogenerated documentation..."
	cd "$(REPO_ROOT)/$(DOCS_DIR)" && uv run --group docs python ../packages/nemo-evaluator-launcher/scripts/autogen_task_yamls.py --docs-root "$(REPO_ROOT)/$(DOCS_DIR)" --docs-format fern
	cd "$(REPO_ROOT)/$(DOCS_DIR)" && uv run --group docs python scripts/generate_api_reference_mdx.py
	@echo "Documentation regenerated!"

docs-help:
	@echo "NeMo Evaluator documentation targets"
	@echo "===================================="
	@echo ""
	@echo "  make docs-autogen    Regenerate benchmark catalog + API reference MDX"
	@echo ""
	@echo "Fern docs (local dev, check, publish):"
	@echo "  make -C docs help"
	@echo "  make -C docs docs              # fern docs dev"
	@echo "  make -C docs docs-check        # fern check + md check"
	@echo ""

# ---------------------------------------------------------------------------
# Container metadata helpers
# ---------------------------------------------------------------------------

container-metadata-verify:
	@echo "Verifying container metadata (digests + checksums)..."
	python scripts/container_metadata_controller.py \
		--mapping-toml "$(MAPPING_TOML)" \
		--all-tasks-irs "$(ALL_TASKS_IRS)" \
		--readme-file "$(README_FILE)" \
		verify

container-metadata-update:
	@echo "Updating container metadata (may modify files)..."
	python scripts/container_metadata_controller.py \
		--mapping-toml "$(MAPPING_TOML)" \
		--all-tasks-irs "$(ALL_TASKS_IRS)" \
		--readme-file "$(README_FILE)" \
		update
	@if [ "$$CI" = "true" ]; then \
		echo "CI mode: failing if update produced changes..."; \
		git status --porcelain; \
		test -z "$$(git status --porcelain)"; \
		git diff --exit-code; \
	fi

# ---------------------------------------------------------------------------
# Config consistency checker (requires Claude Code CLI: `claude`)
# ---------------------------------------------------------------------------

NEL_PKG := $(REPO_ROOT)/packages/nemo-evaluator-launcher
CONFIG_REF := $(NEL_PKG)/.claude/plans/config-templates-reference.md

update-configs:
	@cd "$(NEL_PKG)" && \
	DIFF=$$(git diff main...HEAD -- .); \
	if [ -z "$$DIFF" ]; then \
		echo "CONFIGS_OK"; \
	else \
		{ cat "$(CONFIG_REF)"; \
		  printf '\n---\n\nGit diff (main...HEAD):\n\n```diff\n'; \
		  echo "$$DIFF"; \
		  printf '\n```\n'; } \
		| claude -p --model claude-opus-4-6-1m; \
	fi
