sonar.projectKey=EngHW_FrontierAI_Nemo-Evaluator_Evaluator

sonar.sources=packages/nemo-evaluator/src,packages/nemo-evaluator-launcher/src
sonar.tests=packages/nemo-evaluator/tests,packages/nemo-evaluator-launcher/tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
