sonar.projectKey=EngHW_FrontierAI_Evaluator_NeMo-Evaluator-Next

sonar.sources=src/nemo_evaluator,terraform
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.terraform.provider=aws
sonar.terraform.provider.aws.version=5.0
