# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Tests for SLURM sharded job generation, eval_loop shard_info, and lifecycle."""

import json
from unittest.mock import MagicMock, patch

from nemo_evaluator.config import EvalConfig
from nemo_evaluator.orchestration.slurm_gen import generate_sbatch, write_sbatch


def _make_slurm_config(shards=None, auto_resume=False):
    return EvalConfig.model_validate(
        {
            "services": {
                "model": {
                    "type": "api",
                    "url": "http://x/v1/chat/completions",
                    "protocol": "chat_completions",
                },
            },
            "benchmarks": [
                {"name": "gsm8k", "repeats": 5, "solver": {"type": "simple", "service": "model"}},
            ],
            "cluster": {
                "type": "slurm",
                "walltime": "02:00:00",
                "auto_resume": auto_resume,
                "shards": shards,
                "node_pools": {
                    "compute": {"partition": "batch", "nodes": 1, "gres": "gpu:4"},
                },
            },
        }
    )


class TestSbatchShardGeneration:
    def test_no_shards_no_shard_env(self):
        cfg = _make_slurm_config(shards=None)
        script, _, _ = generate_sbatch(cfg)
        assert "--array" not in script
        assert "NEL_SHARD_IDX" not in script
        assert "nel eval merge" not in script

    def test_per_shard_script_no_array(self):
        cfg = _make_slurm_config(shards=4)
        script, _, _ = generate_sbatch(cfg, shard_idx=0, total_shards=4)
        assert "--array" not in script

    def test_per_shard_exports_env_vars(self):
        cfg = _make_slurm_config(shards=4)
        script, _, _ = generate_sbatch(cfg, shard_idx=2, total_shards=4)
        assert "export NEL_SHARD_IDX=2" in script
        assert "export NEL_TOTAL_SHARDS=4" in script

    def test_per_shard_output_dir(self):
        cfg = _make_slurm_config(shards=4)
        script, _, _ = generate_sbatch(cfg, shard_idx=1, total_shards=4)
        assert "/shard_1" in script

    def test_per_shard_report_only_after_merge(self):
        """Reports are generated by the last shard after merge, not per-shard."""
        cfg = _make_slurm_config(shards=4)
        script, _, _ = generate_sbatch(cfg, shard_idx=0, total_shards=4)
        merge_pos = script.index("nel eval merge")
        report_pos = script.index("nel eval report")
        assert report_pos > merge_pos
        assert (
            "_PARENT_DIR"
            in script.splitlines()[next(idx for idx, ln in enumerate(script.splitlines()) if "nel eval report" in ln)]
        )

    def test_per_shard_has_auto_resume(self):
        """Each shard is an independent job with its own auto_resume chain."""
        cfg = _make_slurm_config(shards=4, auto_resume=True)
        script, _, _ = generate_sbatch(cfg, shard_idx=0, total_shards=4)
        assert "afternotok" in script
        assert "sacct" in script

    def test_per_shard_includes_auto_merge(self):
        cfg = _make_slurm_config(shards=4)
        script, _, _ = generate_sbatch(cfg, shard_idx=0, total_shards=4)
        assert "nel eval merge" in script
        assert ".shard_done" in script
        assert ".merge_lock" in script
        assert "All 4 shards complete" in script

    def test_shard_done_only_on_success(self):
        """Completion marker is only written when NEL_EXIT_CODE is 0."""
        cfg = _make_slurm_config(shards=2)
        script, _, _ = generate_sbatch(cfg, shard_idx=0, total_shards=2)
        assert "if [[ $NEL_EXIT_CODE -eq 0 ]]" in script

    def test_stale_shard_done_cleared_on_start(self):
        """Old .shard_done marker is removed at shard start to prevent stale counts."""
        cfg = _make_slurm_config(shards=3)
        script, _, _ = generate_sbatch(cfg, shard_idx=1, total_shards=3)
        assert 'rm -f "$OUTPUT_DIR/.shard_done"' in script
        rm_pos = script.index('rm -f "$OUTPUT_DIR/.shard_done"')
        touch_pos = script.index('touch "$OUTPUT_DIR/.shard_done"')
        assert rm_pos < touch_pos

    def test_merge_failure_removes_lock(self):
        """Failed merge removes .merge_lock so retries can succeed."""
        cfg = _make_slurm_config(shards=2)
        script, _, _ = generate_sbatch(cfg, shard_idx=0, total_shards=2)
        assert "_MERGE_RC=$?" in script
        assert "rm -rf" in script
        assert ".merge_lock/.done" in script

    def test_merge_success_writes_done_sentinel(self):
        """Successful merge creates .merge_lock/.done sentinel."""
        cfg = _make_slurm_config(shards=2)
        script, _, _ = generate_sbatch(cfg, shard_idx=0, total_shards=2)
        assert 'touch "$_PARENT_DIR/.merge_lock/.done"' in script

    def test_stale_merge_lock_cleaned_before_retry(self):
        """Stale lock (without .done) is removed before mkdir attempt."""
        cfg = _make_slurm_config(shards=2)
        script, _, _ = generate_sbatch(cfg, shard_idx=0, total_shards=2)
        assert '! -f "$_PARENT_DIR/.merge_lock/.done"' in script

    def test_shard_count_uses_stat_not_ls(self):
        """Shard counting uses per-path stat loop, not ls glob (Lustre reliability)."""
        cfg = _make_slurm_config(shards=3)
        script, _, _ = generate_sbatch(cfg, shard_idx=0, total_shards=3)
        assert "ls -1d" not in script
        assert "for _s in $(seq 0" in script
        assert '-f "$_PARENT_DIR/shard_$_s/.shard_done"' in script

    def test_shards_1_edge_case(self):
        """shards=1 produces a single shard script that self-merges."""
        cfg = _make_slurm_config(shards=1)
        script, _, _ = generate_sbatch(cfg, shard_idx=0, total_shards=1)
        assert "export NEL_SHARD_IDX=0" in script
        assert "export NEL_TOTAL_SHARDS=1" in script
        assert "All 1 shards complete" in script

    def test_per_shard_always_has_resume_flag(self):
        """--resume is always passed for shard scripts even without auto_resume."""
        cfg = _make_slurm_config(shards=4, auto_resume=False)
        script, _, _ = generate_sbatch(cfg, shard_idx=0, total_shards=4)
        assert "--resume" in script

    def test_direct_generate_with_shards_rejected(self):
        """Calling generate_sbatch without shard_idx when shards is set should fail."""
        import pytest

        cfg = _make_slurm_config(shards=4)
        with pytest.raises(ValueError, match="write_sbatch"):
            generate_sbatch(cfg)

    def test_no_shards_has_report(self):
        cfg = _make_slurm_config(shards=None)
        script, _, _ = generate_sbatch(cfg)
        assert "nel eval report" in script


class TestAutoresumePrologue:
    def test_autoresume_prologue_in_script(self):
        cfg = _make_slurm_config(auto_resume=True)
        script, _, _ = generate_sbatch(cfg)
        assert "sacct" in script
        assert "afternotok" in script
        assert "_retry_file" in script
        assert "_walltime_file" in script
        assert "_prev_slurm_job_id" in script

    def test_autoresume_disabled(self):
        cfg = _make_slurm_config(auto_resume=False)
        script, _, _ = generate_sbatch(cfg)
        assert "sacct" not in script
        assert "afternotok" not in script

    def test_max_walltime_block_present(self):
        cfg = EvalConfig.model_validate(
            {
                "services": {
                    "model": {
                        "type": "api",
                        "url": "http://x/v1/chat/completions",
                        "protocol": "chat_completions",
                    },
                },
                "benchmarks": [
                    {"name": "gsm8k", "repeats": 5, "solver": {"type": "simple", "service": "model"}},
                ],
                "cluster": {
                    "type": "slurm",
                    "walltime": "02:00:00",
                    "auto_resume": True,
                    "max_walltime": "48:00:00",
                    "node_pools": {
                        "compute": {"partition": "batch", "nodes": 1, "gres": "gpu:4"},
                    },
                },
            }
        )
        script, _, _ = generate_sbatch(cfg)
        assert "172800" in script
        assert "Max walltime" in script

    def test_max_walltime_omitted_when_none(self):
        cfg = _make_slurm_config(auto_resume=True)
        script, _, _ = generate_sbatch(cfg)
        assert "Max walltime" not in script

    def test_max_retries_in_script(self):
        cfg = EvalConfig.model_validate(
            {
                "services": {
                    "model": {
                        "type": "api",
                        "url": "http://x/v1/chat/completions",
                        "protocol": "chat_completions",
                    },
                },
                "benchmarks": [
                    {"name": "gsm8k", "repeats": 5, "solver": {"type": "simple", "service": "model"}},
                ],
                "cluster": {
                    "type": "slurm",
                    "walltime": "02:00:00",
                    "auto_resume": True,
                    "max_retries": 5,
                    "node_pools": {
                        "compute": {"partition": "batch", "nodes": 1, "gres": "gpu:4"},
                    },
                },
            }
        )
        script, _, _ = generate_sbatch(cfg)
        assert "Infra retry limit (5)" in script

    def test_cancelled_handling_in_script(self):
        cfg = _make_slurm_config(auto_resume=True)
        script, _, _ = generate_sbatch(cfg)
        assert "CANCELLED" in script
        assert "was cancelled" in script

    def test_sacct_retry_loop_in_script(self):
        cfg = _make_slurm_config(auto_resume=True)
        script, _, _ = generate_sbatch(cfg)
        assert "_sacct_try" in script
        assert "sleep 2" in script

    def test_sbatch_failure_warning_in_script(self):
        cfg = _make_slurm_config(auto_resume=True)
        script, _, _ = generate_sbatch(cfg)
        assert "WARNING: Failed to submit auto-resume" in script

    def test_prologue_before_cleanup_trap(self):
        cfg = _make_slurm_config(auto_resume=True)
        script, _, _ = generate_sbatch(cfg)
        prologue_pos = script.index("Auto-resume chain")
        trap_pos = script.index("trap cleanup EXIT")
        assert prologue_pos < trap_pos

    def test_max_walltime_days_format(self):
        cfg = EvalConfig.model_validate(
            {
                "services": {
                    "model": {
                        "type": "api",
                        "url": "http://x/v1/chat/completions",
                        "protocol": "chat_completions",
                    },
                },
                "benchmarks": [
                    {"name": "gsm8k", "repeats": 5, "solver": {"type": "simple", "service": "model"}},
                ],
                "cluster": {
                    "type": "slurm",
                    "walltime": "02:00:00",
                    "auto_resume": True,
                    "max_walltime": "2-00:00:00",
                    "node_pools": {
                        "compute": {"partition": "batch", "nodes": 1, "gres": "gpu:4"},
                    },
                },
            }
        )
        script, _, _ = generate_sbatch(cfg)
        assert "172800" in script

    def test_max_walltime_invalid_format_rejected(self):
        import pytest

        with pytest.raises(Exception):
            EvalConfig.model_validate(
                {
                    "services": {
                        "model": {
                            "type": "api",
                            "url": "http://x/v1/chat/completions",
                            "protocol": "chat_completions",
                        },
                    },
                    "benchmarks": [
                        {"name": "gsm8k", "solver": {"type": "simple", "service": "model"}},
                    ],
                    "cluster": {
                        "type": "slurm",
                        "walltime": "02:00:00",
                        "max_walltime": "banana",
                        "node_pools": {
                            "compute": {"partition": "batch", "nodes": 1, "gres": "gpu:4"},
                        },
                    },
                }
            )

    def test_max_retries_negative_rejected(self):
        import pytest

        with pytest.raises(Exception):
            EvalConfig.model_validate(
                {
                    "services": {
                        "model": {
                            "type": "api",
                            "url": "http://x/v1/chat/completions",
                            "protocol": "chat_completions",
                        },
                    },
                    "benchmarks": [
                        {"name": "gsm8k", "solver": {"type": "simple", "service": "model"}},
                    ],
                    "cluster": {
                        "type": "slurm",
                        "walltime": "02:00:00",
                        "max_retries": -1,
                        "node_pools": {
                            "compute": {"partition": "batch", "nodes": 1, "gres": "gpu:4"},
                        },
                    },
                }
            )


class TestPerServiceLogFiles:
    def test_logs_dir_created(self):
        cfg = _make_slurm_config()
        script, _, _ = generate_sbatch(cfg)
        assert 'mkdir -p "$OUTPUT_DIR/logs"' in script

    def test_eval_task_tees_to_log_file(self):
        cfg = _make_slurm_config()
        script, _, _ = generate_sbatch(cfg)
        assert "tee" in script
        assert "logs/eval-" in script
        assert "PIPESTATUS" in script

    def test_vllm_service_log_redirect(self):
        cfg = EvalConfig.model_validate(
            {
                "services": {
                    "model": {
                        "type": "vllm",
                        "model": "m",
                        "protocol": "chat_completions",
                        "port": 8000,
                    },
                },
                "benchmarks": [
                    {"name": "gsm8k", "solver": {"type": "simple", "service": "model"}},
                ],
                "cluster": {
                    "type": "slurm",
                    "walltime": "02:00:00",
                    "node_pools": {
                        "compute": {"partition": "batch", "nodes": 1, "gres": "gpu:4"},
                    },
                },
            }
        )
        script, _, _ = generate_sbatch(cfg)
        assert "logs/server-model.log" in script


class TestWriteSbatchSharding:
    """Integration tests for write_sbatch with shards."""

    def test_write_sbatch_creates_per_shard_dirs(self, tmp_path):
        cfg = _make_slurm_config(shards=3)
        cfg.output.dir = str(tmp_path / "run")
        cfg.output.timestamped = False
        script_paths, extra_paths = write_sbatch(cfg, output_dir=tmp_path / "run")
        assert len(script_paths) == 3
        for i, sp in enumerate(script_paths):
            assert sp.parent.name == f"shard_{i}"
            assert sp.name == "nel_eval.sbatch"
            assert sp.exists()
            content = sp.read_text()
            assert f"export NEL_SHARD_IDX={i}" in content
            assert "export NEL_TOTAL_SHARDS=3" in content

    def test_write_sbatch_no_shards_returns_single_list(self, tmp_path):
        cfg = _make_slurm_config(shards=None)
        cfg.output.dir = str(tmp_path / "run")
        cfg.output.timestamped = False
        script_paths, extra_paths = write_sbatch(cfg, output_dir=tmp_path / "run")
        assert isinstance(script_paths, list)
        assert len(script_paths) == 1
        assert script_paths[0].name == "nel_eval.sbatch"

    def test_write_sbatch_shard_sidecars_per_dir(self, tmp_path):
        """Each shard dir gets its own sidecar config."""
        cfg = EvalConfig.model_validate(
            {
                "services": {
                    "model": {"type": "api", "url": "http://x/v1/chat/completions", "protocol": "chat_completions"}
                },
                "benchmarks": [
                    {
                        "name": "harbor://swebench-verified@1.0",
                        "solver": {"type": "harbor", "service": "model", "agent": "openhands"},
                        "sandbox": {"type": "ecs_fargate", "region": "us-west-2"},
                    }
                ],
                "cluster": {
                    "type": "slurm",
                    "walltime": "02:00:00",
                    "shards": 2,
                    "node_pools": {"compute": {"partition": "batch", "nodes": 1}},
                },
            }
        )
        cfg.output.dir = str(tmp_path / "run")
        cfg.output.timestamped = False
        script_paths, extra_paths = write_sbatch(cfg, output_dir=tmp_path / "run")
        assert len(script_paths) == 2
        sidecar_files = [p for p in extra_paths if p.name.startswith("config_")]
        assert len(sidecar_files) == 2
        assert sidecar_files[0].parent.name == "shard_0"
        assert sidecar_files[1].parent.name == "shard_1"


class TestSidecarConfigGeneration:
    """Complex benchmarks (harbor solver + ecs sandbox) generate sidecar YAML."""

    def test_harbor_bench_gets_sidecar(self):
        cfg = EvalConfig.model_validate(
            {
                "services": {
                    "model": {
                        "type": "api",
                        "url": "http://x/v1/chat/completions",
                        "protocol": "chat_completions",
                    },
                },
                "benchmarks": [
                    {
                        "name": "harbor://swebench-verified@1.0",
                        "solver": {"type": "harbor", "service": "model", "agent": "openhands-sdk"},
                        "sandbox": {"type": "ecs_fargate", "region": "us-west-2"},
                    }
                ],
                "cluster": {
                    "type": "slurm",
                    "walltime": "02:00:00",
                    "node_pools": {"compute": {"partition": "batch", "nodes": 1}},
                },
            }
        )
        script, sidecars, _ = generate_sbatch(cfg)
        assert len(sidecars) == 1
        key = list(sidecars.keys())[0]
        sidecar = sidecars[key]
        assert sidecar["services"]["model"]["type"] == "api"
        assert "${MODEL_URL}" in sidecar["services"]["model"]["url"]
        assert "${MODEL_MODEL}" in sidecar["services"]["model"]["model"]
        assert sidecar["benchmarks"][0]["solver"]["type"] == "harbor"
        assert sidecar["benchmarks"][0]["sandbox"]["type"] == "ecs_fargate"
        assert "nel eval run" in script
        assert f"config_{key}.yaml" in script
        assert "srun --overlap" not in script.split("nel eval run")[0].split("Benchmark 1/1")[-1]

    def test_simple_bench_uses_quick_mode(self):
        cfg = EvalConfig.model_validate(
            {
                "services": {
                    "model": {
                        "type": "api",
                        "url": "http://x/v1/chat/completions",
                        "protocol": "chat_completions",
                    },
                },
                "benchmarks": [
                    {
                        "name": "gsm8k",
                        "solver": {"type": "simple", "service": "model"},
                    }
                ],
                "cluster": {
                    "type": "slurm",
                    "walltime": "02:00:00",
                    "node_pools": {"compute": {"partition": "batch", "nodes": 1}},
                },
            }
        )
        script, sidecars, _ = generate_sbatch(cfg)
        assert len(sidecars) == 0
        assert '--bench "gsm8k"' in script

    def test_secrets_not_in_sbatch_script(self):
        """Credentials must go to .secrets.env, not inline in the sbatch script."""
        cfg = EvalConfig.model_validate(
            {
                "services": {
                    "model": {
                        "type": "api",
                        "url": "http://x/v1/chat/completions",
                        "protocol": "chat_completions",
                    },
                },
                "benchmarks": [
                    {
                        "name": "gsm8k",
                        "solver": {"type": "simple", "service": "model"},
                    }
                ],
                "cluster": {
                    "type": "slurm",
                    "walltime": "02:00:00",
                    "container_env": {
                        "HF_TOKEN": "hf_SUPERSECRET1234",
                        "AWS_SECRET_ACCESS_KEY": "wJalrXUtnFEMI/K7MDENG",
                    },
                    "node_pools": {"compute": {"partition": "batch", "nodes": 1}},
                },
            }
        )
        script, _, secrets_result = generate_sbatch(cfg)
        assert "hf_SUPERSECRET1234" not in script
        assert "wJalrXUtnFEMI/K7MDENG" not in script
        assert "source" in script and ".secrets.env" in script
        assert "hf_SUPERSECRET1234" in secrets_result.secrets_content
        assert "wJalrXUtnFEMI/K7MDENG" in secrets_result.secrets_content

    def test_per_service_env_isolation(self):
        """Different services with same env var name get disambiguated keys."""
        cfg = EvalConfig.model_validate(
            {
                "services": {
                    "svc_a": {
                        "type": "vllm",
                        "model": "model-a",
                        "protocol": "chat_completions",
                        "port": 8000,
                        "extra_env": {"HF_TOKEN": "token_for_a"},
                    },
                    "svc_b": {
                        "type": "vllm",
                        "model": "model-b",
                        "protocol": "chat_completions",
                        "port": 8001,
                        "extra_env": {"HF_TOKEN": "token_for_b"},
                    },
                },
                "benchmarks": [
                    {
                        "name": "gsm8k",
                        "solver": {"type": "simple", "service": "svc_a"},
                    }
                ],
                "cluster": {
                    "type": "slurm",
                    "walltime": "02:00:00",
                    "node_pools": {"compute": {"partition": "batch", "nodes": 1, "gres": "gpu:4"}},
                },
            }
        )
        script, _, secrets_result = generate_sbatch(cfg)
        # Both values in .secrets.env under disambiguated names
        assert "token_for_a" in secrets_result.secrets_content
        assert "token_for_b" in secrets_result.secrets_content
        # Neither plaintext value appears in the script
        assert "token_for_a" not in script
        assert "token_for_b" not in script
        # Re-export commands present before srun
        assert 'export HF_TOKEN="$' in script

    def test_shards_plus_sidecar_works(self):
        """Sharding with complex (Harbor) benchmarks generates per-shard scripts with sidecars."""
        cfg = EvalConfig.model_validate(
            {
                "services": {
                    "model": {
                        "type": "api",
                        "url": "http://x/v1/chat/completions",
                        "protocol": "chat_completions",
                    },
                },
                "benchmarks": [
                    {
                        "name": "harbor://swebench-verified@1.0",
                        "solver": {"type": "harbor", "service": "model", "agent": "openhands"},
                        "sandbox": {"type": "ecs_fargate", "region": "us-west-2"},
                    }
                ],
                "cluster": {
                    "type": "slurm",
                    "walltime": "02:00:00",
                    "shards": 4,
                    "auto_resume": True,
                    "node_pools": {"compute": {"partition": "batch", "nodes": 1}},
                },
            }
        )
        script, sidecars, _ = generate_sbatch(cfg, shard_idx=0, total_shards=4)
        assert len(sidecars) == 1
        assert "export NEL_SHARD_IDX=0" in script
        assert "export NEL_TOTAL_SHARDS=4" in script
        assert "--resume" in script
        assert "afternotok" in script
        assert "nel eval run" in script
        assert "/shard_0" in script


class TestShardInfoComputation:
    """Test that shard_info correctly computes problem_range via get_shard_range."""

    def test_shard_info_computes_range(self):
        from nemo_evaluator.engine.sharding import get_shard_range

        ds_size = 100
        shard_idx, total_shards = 0, 4
        problem_range = get_shard_range(ds_size, shard_idx, total_shards)
        assert problem_range == (0, 25)

    def test_shard_info_with_max_problems(self):
        from nemo_evaluator.engine.sharding import get_shard_range

        ds_size = 1000
        max_problems = 50
        effective = min(ds_size, max_problems)
        problem_range = get_shard_range(effective, 1, 4)
        assert problem_range == (13, 26)

    def test_shard_info_respects_effective_size(self):
        """Sharding must use min(ds_size, max_problems), not raw ds_size."""
        from nemo_evaluator.engine.sharding import get_shard_range

        ranges = [get_shard_range(50, i, 4) for i in range(4)]
        all_indices = set()
        for s, e in ranges:
            all_indices.update(range(s, e))
        assert len(all_indices) == 50
        assert min(all_indices) == 0
        assert max(all_indices) == 49


class TestSbatchExtraFlags:
    """sbatch_extra_flags and sbatch_comment support."""

    def test_sbatch_extra_flags_in_header(self):
        cfg = EvalConfig.model_validate(
            {
                "services": {
                    "model": {
                        "type": "api",
                        "url": "http://x/v1/chat/completions",
                        "protocol": "chat_completions",
                    },
                },
                "benchmarks": [
                    {"name": "gsm8k", "solver": {"type": "simple", "service": "model"}},
                ],
                "cluster": {
                    "type": "slurm",
                    "walltime": "02:00:00",
                    "sbatch_extra_flags": {"switches": 1, "exclusive": True},
                    "node_pools": {"compute": {"partition": "batch", "nodes": 1}},
                },
            }
        )
        script, _, _ = generate_sbatch(cfg)
        assert "#SBATCH --switches=1" in script
        assert "#SBATCH --exclusive" in script

    def test_sbatch_comment_in_header(self):
        cfg = EvalConfig.model_validate(
            {
                "services": {
                    "model": {
                        "type": "api",
                        "url": "http://x/v1/chat/completions",
                        "protocol": "chat_completions",
                    },
                },
                "benchmarks": [
                    {"name": "gsm8k", "solver": {"type": "simple", "service": "model"}},
                ],
                "cluster": {
                    "type": "slurm",
                    "walltime": "02:00:00",
                    "sbatch_comment": "my eval run",
                    "node_pools": {"compute": {"partition": "batch", "nodes": 1}},
                },
            }
        )
        script, _, _ = generate_sbatch(cfg)
        assert "#SBATCH --comment=" in script
        assert "my eval run" in script

    def test_no_requeue_always_present(self):
        cfg = _make_slurm_config()
        script, _, _ = generate_sbatch(cfg)
        assert "#SBATCH --no-requeue" in script

    def test_sbatch_false_flag_omitted(self):
        cfg = EvalConfig.model_validate(
            {
                "services": {
                    "model": {
                        "type": "api",
                        "url": "http://x/v1/chat/completions",
                        "protocol": "chat_completions",
                    },
                },
                "benchmarks": [
                    {"name": "gsm8k", "solver": {"type": "simple", "service": "model"}},
                ],
                "cluster": {
                    "type": "slurm",
                    "walltime": "02:00:00",
                    "sbatch_extra_flags": {"exclusive": False},
                    "node_pools": {"compute": {"partition": "batch", "nodes": 1}},
                },
            }
        )
        script, _, _ = generate_sbatch(cfg)
        assert "#SBATCH --exclusive" not in script


class TestLogPersistence:
    """Log filenames contain $SLURM_JOB_ID and have symlinks."""

    def test_service_log_contains_job_id(self):
        cfg = EvalConfig.model_validate(
            {
                "services": {
                    "model": {
                        "type": "vllm",
                        "model": "m",
                        "protocol": "chat_completions",
                        "port": 8000,
                    },
                },
                "benchmarks": [
                    {"name": "gsm8k", "solver": {"type": "simple", "service": "model"}},
                ],
                "cluster": {
                    "type": "slurm",
                    "walltime": "02:00:00",
                    "node_pools": {"compute": {"partition": "batch", "nodes": 1, "gres": "gpu:4"}},
                },
            }
        )
        script, _, _ = generate_sbatch(cfg)
        assert "server-model-$SLURM_JOB_ID.log" in script
        assert 'ln -sf "server-model-$SLURM_JOB_ID.log"' in script

    def test_eval_log_contains_job_id(self):
        cfg = _make_slurm_config()
        script, _, _ = generate_sbatch(cfg)
        assert "eval-gsm8k-$SLURM_JOB_ID.log" in script
        assert 'ln -sf "eval-gsm8k-$SLURM_JOB_ID.log"' in script

    def test_eval_log_uses_append(self):
        cfg = _make_slurm_config()
        script, _, _ = generate_sbatch(cfg)
        assert "tee -a" in script

    def test_service_log_uses_append(self):
        cfg = EvalConfig.model_validate(
            {
                "services": {
                    "model": {
                        "type": "vllm",
                        "model": "m",
                        "protocol": "chat_completions",
                        "port": 8000,
                    },
                },
                "benchmarks": [
                    {"name": "gsm8k", "solver": {"type": "simple", "service": "model"}},
                ],
                "cluster": {
                    "type": "slurm",
                    "walltime": "02:00:00",
                    "node_pools": {"compute": {"partition": "batch", "nodes": 1, "gres": "gpu:4"}},
                },
            }
        )
        script, _, _ = generate_sbatch(cfg)
        assert ">>" in script


class TestMpiPmix:
    """All srun commands include --mpi=pmix."""

    def test_service_srun_has_mpi_pmix(self):
        cfg = EvalConfig.model_validate(
            {
                "services": {
                    "model": {
                        "type": "vllm",
                        "model": "m",
                        "protocol": "chat_completions",
                        "port": 8000,
                        "image": "vllm/vllm:latest",
                    },
                },
                "benchmarks": [
                    {"name": "gsm8k", "solver": {"type": "simple", "service": "model"}},
                ],
                "cluster": {
                    "type": "slurm",
                    "walltime": "02:00:00",
                    "node_pools": {"compute": {"partition": "batch", "nodes": 1, "gres": "gpu:4"}},
                },
            }
        )
        script, _, _ = generate_sbatch(cfg)
        assert "--mpi=pmix" in script

    def test_eval_srun_has_mpi_pmix(self):
        cfg = EvalConfig.model_validate(
            {
                "services": {
                    "model": {
                        "type": "api",
                        "url": "http://x/v1/chat/completions",
                        "protocol": "chat_completions",
                    },
                },
                "benchmarks": [
                    {"name": "gsm8k", "solver": {"type": "simple", "service": "model"}},
                ],
                "cluster": {
                    "type": "slurm",
                    "walltime": "02:00:00",
                    "eval_image": "nel:latest",
                    "node_pools": {"compute": {"partition": "batch", "nodes": 1}},
                },
            }
        )
        script, _, _ = generate_sbatch(cfg)
        assert "--mpi=pmix" in script


class TestGpusPerNode:
    """gpus_per_node on NodePool generates the #SBATCH --gpus-per-node directive."""

    def test_gpus_per_node_in_header(self):
        cfg = EvalConfig.model_validate(
            {
                "services": {
                    "model": {
                        "type": "api",
                        "url": "http://x/v1/chat/completions",
                        "protocol": "chat_completions",
                    },
                },
                "benchmarks": [
                    {"name": "gsm8k", "solver": {"type": "simple", "service": "model"}},
                ],
                "cluster": {
                    "type": "slurm",
                    "walltime": "02:00:00",
                    "node_pools": {"compute": {"partition": "batch", "nodes": 1, "gpus_per_node": 8}},
                },
            }
        )
        script, _, _ = generate_sbatch(cfg)
        assert "#SBATCH --gpus-per-node=8" in script

    def test_gpus_per_node_absent_when_none(self):
        cfg = _make_slurm_config()
        script, _, _ = generate_sbatch(cfg)
        assert "--gpus-per-node" not in script


class TestMultinodeRay:
    """Multi-node Ray deployment templates."""

    def test_multinode_vllm_generates_ray_template(self):
        cfg = EvalConfig.model_validate(
            {
                "services": {
                    "model": {
                        "type": "vllm",
                        "model": "nvidia/model",
                        "protocol": "chat_completions",
                        "port": 8000,
                        "tensor_parallel_size": 8,
                        "num_nodes": 2,
                    },
                },
                "benchmarks": [
                    {"name": "gsm8k", "solver": {"type": "simple", "service": "model"}},
                ],
                "cluster": {
                    "type": "slurm",
                    "walltime": "04:00:00",
                    "node_pools": {"compute": {"partition": "batch", "nodes": 2, "gres": "gpu:8"}},
                },
            }
        )
        script, _, _ = generate_sbatch(cfg)
        assert "multi-node Ray" in script
        assert "ray start --head" in script
        assert "ray start --address" in script
        assert "--distributed-executor-backend ray" in script

    def test_multinode_ip_discovery(self):
        cfg = EvalConfig.model_validate(
            {
                "services": {
                    "model": {
                        "type": "vllm",
                        "model": "nvidia/model",
                        "protocol": "chat_completions",
                        "port": 8000,
                        "tensor_parallel_size": 8,
                        "num_nodes": 2,
                    },
                },
                "benchmarks": [
                    {"name": "gsm8k", "solver": {"type": "simple", "service": "model"}},
                ],
                "cluster": {
                    "type": "slurm",
                    "walltime": "04:00:00",
                    "node_pools": {"compute": {"partition": "batch", "nodes": 2, "gres": "gpu:8"}},
                },
            }
        )
        script, _, _ = generate_sbatch(cfg)
        assert "MASTER_IP=" in script
        assert "scontrol show hostname" in script
        assert "export MASTER_IP" in script

    def test_singlenode_no_ray(self):
        cfg = EvalConfig.model_validate(
            {
                "services": {
                    "model": {
                        "type": "vllm",
                        "model": "m",
                        "protocol": "chat_completions",
                        "port": 8000,
                    },
                },
                "benchmarks": [
                    {"name": "gsm8k", "solver": {"type": "simple", "service": "model"}},
                ],
                "cluster": {
                    "type": "slurm",
                    "walltime": "02:00:00",
                    "node_pools": {"compute": {"partition": "batch", "nodes": 1, "gres": "gpu:4"}},
                },
            }
        )
        script, _, _ = generate_sbatch(cfg)
        assert "ray start" not in script
        assert "MASTER_IP" not in script

    def test_multinode_srun_ntasks_matches_nodes(self):
        cfg = EvalConfig.model_validate(
            {
                "services": {
                    "model": {
                        "type": "vllm",
                        "model": "nvidia/model",
                        "protocol": "chat_completions",
                        "port": 8000,
                        "tensor_parallel_size": 8,
                        "num_nodes": 4,
                        "image": "vllm:latest",
                    },
                },
                "benchmarks": [
                    {"name": "gsm8k", "solver": {"type": "simple", "service": "model"}},
                ],
                "cluster": {
                    "type": "slurm",
                    "walltime": "04:00:00",
                    "node_pools": {"compute": {"partition": "batch", "nodes": 4, "gres": "gpu:8"}},
                },
            }
        )
        script, _, _ = generate_sbatch(cfg)
        assert "--ntasks 4" in script


# ---------------------------------------------------------------------------
# Lifecycle helpers
# ---------------------------------------------------------------------------


class TestGetJobIds:
    def test_from_job_ids_list(self):
        from nemo_evaluator.executors.slurm_executor import _get_job_ids

        meta = {"job_id": "100", "job_ids": ["100", "101", "102"]}
        assert _get_job_ids(meta) == ["100", "101", "102"]

    def test_from_scalar_job_id(self):
        from nemo_evaluator.executors.slurm_executor import _get_job_ids

        meta = {"job_id": "100"}
        assert _get_job_ids(meta) == ["100"]

    def test_empty_meta(self):
        from nemo_evaluator.executors.slurm_executor import _get_job_ids

        assert _get_job_ids({}) == []

    def test_old_run_no_job_ids_key(self):
        from nemo_evaluator.executors.slurm_executor import _get_job_ids

        meta = {"job_id": "555", "hostname": "h"}
        assert _get_job_ids(meta) == ["555"]


class TestIsSharded:
    def test_sharded(self):
        from nemo_evaluator.executors.slurm_executor import _is_sharded

        assert _is_sharded({"job_ids": ["1", "2"]}) is True

    def test_not_sharded(self):
        from nemo_evaluator.executors.slurm_executor import _is_sharded

        assert _is_sharded({"job_id": "1"}) is False


# ---------------------------------------------------------------------------
# Sharded status
# ---------------------------------------------------------------------------


class TestShardedStatus:
    def _make_meta(self, job_ids):
        return {
            "job_id": job_ids[0],
            "job_ids": job_ids,
            "hostname": "login01",
            "remote_dir": "/run/parent",
            "username": "user",
            "is_sharded": True,
        }

    @patch("nemo_evaluator.executors.slurm_executor._read_meta")
    @patch("nemo_evaluator.executors.slurm_executor._resolve_shard_latest_ids")
    @patch("nemo_evaluator.executors.ssh.batch_check_job_status")
    @patch("nemo_evaluator.executors.ssh.ssh_run", return_value="PENDING")
    def test_status_aggregates_shards(self, mock_ssh, mock_batch, mock_latest, mock_meta):
        from nemo_evaluator.executors.slurm_executor import SlurmExecutor

        job_ids = ["100", "101", "102"]
        mock_meta.return_value = self._make_meta(job_ids)
        mock_latest.return_value = job_ids
        mock_batch.return_value = {
            "100": {"job_id": "100", "state": "COMPLETED"},
            "101": {"job_id": "101", "state": "RUNNING", "time": "1:30:00"},
            "102": {"job_id": "102", "state": "PENDING"},
        }

        ex = SlurmExecutor()
        state = ex.status("/run/parent")

        assert state.running is True
        assert "shard_0" in state.details
        assert "shard_1" in state.details
        assert "shard_2" in state.details
        assert "COMPLETED" in state.details["shard_0"]
        assert "RUNNING" in state.details["shard_1"]
        assert "1/3 COMPLETED" in state.details["shards"]

    @patch("nemo_evaluator.executors.slurm_executor._read_meta")
    @patch("nemo_evaluator.executors.ssh.check_job_status")
    def test_status_single_job_unchanged(self, mock_check, mock_meta):
        from nemo_evaluator.executors.slurm_executor import SlurmExecutor

        mock_meta.return_value = {"job_id": "100", "hostname": "h", "username": ""}
        mock_check.return_value = {"job_id": "100", "state": "RUNNING"}

        state = SlurmExecutor().status("/out")
        assert state.running is True
        assert state.details["state"] == "RUNNING"

    @patch("nemo_evaluator.executors.slurm_executor._read_meta")
    @patch("nemo_evaluator.executors.slurm_executor._resolve_shard_latest_ids")
    @patch("nemo_evaluator.executors.ssh.batch_check_job_status")
    @patch("nemo_evaluator.executors.ssh.ssh_run", return_value="DONE")
    def test_status_merge_done(self, mock_ssh, mock_batch, mock_latest, mock_meta):
        from nemo_evaluator.executors.slurm_executor import SlurmExecutor

        job_ids = ["10", "11"]
        mock_meta.return_value = self._make_meta(job_ids)
        mock_latest.return_value = job_ids
        mock_batch.return_value = {
            "10": {"job_id": "10", "state": "COMPLETED"},
            "11": {"job_id": "11", "state": "COMPLETED"},
        }

        state = SlurmExecutor().status("/run/parent")
        assert state.running is False
        assert state.details.get("merge") == "DONE"


# ---------------------------------------------------------------------------
# Eval progress
# ---------------------------------------------------------------------------


class TestFetchEvalProgress:
    def test_parse_wc_output_sharded(self):
        import pytest
        from nemo_evaluator.executors.slurm_executor import _fetch_eval_progress

        ssh_output = (
            "  45 /run/shard_0/bench/verified_log.jsonl\n"
            " 100 /run/shard_1/bench/verified_log.jsonl\n"
            "   0 /run/shard_2/bench/verified_log.jsonl\n"
            " 145 total\n"
            "---\n"
            "eval start: bench problems=100 [0:100] repeats=1 concurrency=30\n"
            "---\n"
            "/run/shard_0/bench/verified_log.jsonl 45 22.500000\n"
            "/run/shard_1/bench/verified_log.jsonl 100 61.000000\n"
        )
        with patch("nemo_evaluator.executors.ssh.ssh_run", return_value=ssh_output):
            result = _fetch_eval_progress("host", "/run", shard_count=3, username="u")

        assert result["shard_0"].done == 45
        assert result["shard_0"].expected == 100
        assert result["shard_0"].avg_reward == pytest.approx(0.5)
        assert result["shard_1"].done == 100
        assert result["shard_1"].expected == 100
        assert result["shard_1"].avg_reward == pytest.approx(0.61)
        assert result["shard_2"].done == 0
        assert result["shard_2"].expected == 100
        assert result["shard_2"].avg_reward is None

    def test_no_verified_log_yet(self):
        from nemo_evaluator.executors.slurm_executor import _fetch_eval_progress

        with patch("nemo_evaluator.executors.ssh.ssh_run", return_value="---\n---\n"):
            result = _fetch_eval_progress("host", "/run", shard_count=2, username="u")

        assert result == {}

    def test_non_sharded(self):
        import pytest
        from nemo_evaluator.executors.slurm_executor import _fetch_eval_progress

        ssh_output = (
            "  42 /run/bench/verified_log.jsonl\n"
            "---\n"
            "eval start: bench problems=500 [0:500] repeats=1 concurrency=30\n"
            "---\n"
            "/run/bench/verified_log.jsonl 42 12.600000\n"
        )
        with patch("nemo_evaluator.executors.ssh.ssh_run", return_value=ssh_output):
            result = _fetch_eval_progress("host", "/run", username="u")

        assert result["root"].done == 42
        assert result["root"].expected == 500
        assert result["root"].avg_reward == pytest.approx(0.3)

    def test_no_log_yet(self):
        from nemo_evaluator.executors.slurm_executor import _fetch_eval_progress

        ssh_output = "  15 /run/shard_0/bench/verified_log.jsonl\n---\n\n---\n\n"
        with patch("nemo_evaluator.executors.ssh.ssh_run", return_value=ssh_output):
            result = _fetch_eval_progress("host", "/run", shard_count=1, username="u")

        assert result["shard_0"].done == 15
        assert result["shard_0"].expected is None


class TestProgressLabel:
    def test_with_expected(self):
        from nemo_evaluator.executors.slurm_executor import _ShardProgress, _progress_label

        assert _progress_label(_ShardProgress(45, 100)) == "45/100 (45%)"
        assert _progress_label(_ShardProgress(100, 100)) == "100/100 (100%)"
        assert _progress_label(_ShardProgress(0, 100)) == "0/100 (0%)"

    def test_without_expected(self):
        from nemo_evaluator.executors.slurm_executor import _ShardProgress, _progress_label

        assert _progress_label(_ShardProgress(42, None)) == "42 verified"

    def test_rounding(self):
        from nemo_evaluator.executors.slurm_executor import _ShardProgress, _progress_label

        assert _progress_label(_ShardProgress(1, 3)) == "1/3 (33%)"
        assert _progress_label(_ShardProgress(2, 3)) == "2/3 (67%)"

    def test_with_reward(self):
        from nemo_evaluator.executors.slurm_executor import _ShardProgress, _progress_label

        assert _progress_label(_ShardProgress(45, 100, 22.5, 45)) == "45/100 (45%), avg_reward=0.5000"
        assert _progress_label(_ShardProgress(10, None, 3.0, 10)) == "10 verified, avg_reward=0.3000"


class TestStatusWithProgress:
    def _make_meta(self, job_ids):
        return {
            "job_id": job_ids[0],
            "job_ids": job_ids,
            "hostname": "login01",
            "remote_dir": "/run/parent",
            "username": "user",
            "is_sharded": True,
        }

    @patch("nemo_evaluator.executors.slurm_executor._read_meta")
    @patch("nemo_evaluator.executors.slurm_executor._resolve_shard_latest_ids")
    @patch("nemo_evaluator.executors.ssh.batch_check_job_status")
    @patch("nemo_evaluator.executors.slurm_executor._fetch_eval_progress")
    @patch("nemo_evaluator.executors.ssh.ssh_run", return_value="PENDING")
    def test_sharded_status_shows_progress(self, mock_ssh, mock_progress, mock_batch, mock_latest, mock_meta):
        from nemo_evaluator.executors.slurm_executor import _ShardProgress, SlurmExecutor

        job_ids = ["100", "101"]
        mock_meta.return_value = self._make_meta(job_ids)
        mock_latest.return_value = job_ids
        mock_batch.return_value = {
            "100": {"job_id": "100", "state": "RUNNING", "time": "1:00:00"},
            "101": {"job_id": "101", "state": "RUNNING", "time": "0:30:00"},
        }
        mock_progress.return_value = {
            "shard_0": _ShardProgress(45, 100, 22.5, 45),
            "shard_1": _ShardProgress(12, 100, 3.6, 12),
        }

        state = SlurmExecutor().status("/run/parent")

        assert "progress: 45/100 (45%), avg_reward=0.5000" in state.details["shard_0"]
        assert "progress: 12/100 (12%), avg_reward=0.3000" in state.details["shard_1"]
        assert "progress: 57/200 (28%), avg_reward=0.4579" in state.details["shards"]

    @patch("nemo_evaluator.executors.slurm_executor._read_meta")
    @patch("nemo_evaluator.executors.slurm_executor._resolve_shard_latest_ids")
    @patch("nemo_evaluator.executors.ssh.batch_check_job_status")
    @patch("nemo_evaluator.executors.slurm_executor._fetch_eval_progress")
    @patch("nemo_evaluator.executors.ssh.ssh_run", return_value="PENDING")
    def test_progress_unavailable_does_not_break_status(
        self, mock_ssh, mock_progress, mock_batch, mock_latest, mock_meta
    ):
        from nemo_evaluator.executors.slurm_executor import SlurmExecutor

        job_ids = ["100", "101"]
        mock_meta.return_value = self._make_meta(job_ids)
        mock_latest.return_value = job_ids
        mock_batch.return_value = {
            "100": {"job_id": "100", "state": "PENDING"},
            "101": {"job_id": "101", "state": "PENDING"},
        }
        mock_progress.side_effect = Exception("SSH timeout")

        state = SlurmExecutor().status("/run/parent")

        assert "shard_0" in state.details
        assert "progress" not in state.details["shard_0"]

    @patch("nemo_evaluator.executors.slurm_executor._read_meta")
    @patch("nemo_evaluator.executors.ssh.check_job_status")
    @patch("nemo_evaluator.executors.slurm_executor._fetch_eval_progress")
    def test_non_sharded_status_shows_progress(self, mock_progress, mock_check, mock_meta):
        from nemo_evaluator.executors.slurm_executor import _ShardProgress, SlurmExecutor

        mock_meta.return_value = {"job_id": "100", "hostname": "h", "username": ""}
        mock_check.return_value = {"job_id": "100", "state": "RUNNING"}
        mock_progress.return_value = {"root": _ShardProgress(42, 500, 12.6, 42)}

        state = SlurmExecutor().status("/out")
        assert state.details.get("progress") == "42/500 (8%), avg_reward=0.3000"


# ---------------------------------------------------------------------------
# Sharded stop
# ---------------------------------------------------------------------------


class TestShardedStop:
    @patch("nemo_evaluator.executors.slurm_executor._read_meta")
    @patch("nemo_evaluator.executors.slurm_executor._resolve_shard_latest_ids")
    @patch("nemo_evaluator.executors.ssh.ssh_run")
    def test_stop_all_shards(self, mock_ssh, mock_latest, mock_meta):
        from nemo_evaluator.executors.slurm_executor import SlurmExecutor

        job_ids = ["10", "11", "12"]
        mock_meta.return_value = {
            "job_id": "10",
            "job_ids": job_ids,
            "hostname": "h",
            "remote_dir": "/r",
            "username": "",
            "is_sharded": True,
        }
        mock_latest.return_value = ["10", "11", "12"]
        mock_ssh.return_value = ""

        assert SlurmExecutor().stop("/r") is True
        mock_ssh.assert_called_once()
        call_cmd = mock_ssh.call_args[0][1]
        assert "scancel 10 11 12" in call_cmd

    @patch("nemo_evaluator.executors.slurm_executor._read_meta")
    @patch("nemo_evaluator.executors.slurm_executor._resolve_latest_job_id")
    @patch("nemo_evaluator.executors.ssh.cancel_job")
    def test_stop_single_shard(self, mock_cancel, mock_latest, mock_meta):
        from nemo_evaluator.executors.slurm_executor import SlurmExecutor

        mock_meta.return_value = {
            "job_id": "10",
            "job_ids": ["10", "11"],
            "hostname": "h",
            "remote_dir": "/r",
            "username": "",
            "is_sharded": True,
        }
        mock_latest.return_value = "11"

        assert SlurmExecutor().stop("/r", shard_idx=1) is True
        mock_cancel.assert_called_once_with(hostname="h", job_id="11", username=None)

    @patch("nemo_evaluator.executors.slurm_executor._read_meta")
    def test_stop_shard_out_of_range(self, mock_meta):
        from nemo_evaluator.executors.slurm_executor import SlurmExecutor

        mock_meta.return_value = {
            "job_id": "10",
            "job_ids": ["10", "11"],
            "hostname": "h",
            "remote_dir": "/r",
            "username": "",
            "is_sharded": True,
        }
        assert SlurmExecutor().stop("/r", shard_idx=5) is False


# ---------------------------------------------------------------------------
# Sharded logs
# ---------------------------------------------------------------------------


class TestShardedLogs:
    @patch("nemo_evaluator.executors.slurm_executor._read_meta")
    @patch("nemo_evaluator.executors.ssh.ssh_run")
    def test_logs_summary_default(self, mock_ssh, mock_meta):
        from nemo_evaluator.executors.slurm_executor import SlurmExecutor

        mock_meta.return_value = {
            "job_id": "10",
            "job_ids": ["10", "11"],
            "hostname": "h",
            "remote_dir": "/r",
            "username": "",
            "is_sharded": True,
        }
        mock_ssh.return_value = "=== shard_0 ===\nlog0\n\n=== shard_1 ===\nlog1"

        content = SlurmExecutor().logs("/r")
        assert content is not None
        assert "shard_0" in content or "log0" in content
        mock_ssh.assert_called_once()
        call_cmd = mock_ssh.call_args[0][1]
        assert "tail -n 20" in call_cmd

    @patch("nemo_evaluator.executors.slurm_executor._read_meta")
    @patch("nemo_evaluator.executors.slurm_executor._resolve_latest_job_id")
    @patch("nemo_evaluator.executors.ssh.ssh_run")
    def test_logs_specific_shard(self, mock_ssh, mock_latest, mock_meta):
        from nemo_evaluator.executors.slurm_executor import SlurmExecutor

        mock_meta.return_value = {
            "job_id": "10",
            "job_ids": ["10", "11"],
            "hostname": "h",
            "remote_dir": "/r",
            "username": "",
            "is_sharded": True,
        }
        mock_latest.return_value = "11"
        mock_ssh.return_value = "full log for shard 1"

        content = SlurmExecutor().logs("/r", shard_idx=1)
        assert content == "full log for shard 1"
        call_cmd = mock_ssh.call_args[0][1]
        assert "/r/shard_1/logs/slurm-11.log" in call_cmd

    @patch("nemo_evaluator.executors.slurm_executor._read_meta")
    def test_logs_shard_out_of_range(self, mock_meta):
        from nemo_evaluator.executors.slurm_executor import SlurmExecutor

        mock_meta.return_value = {
            "job_id": "10",
            "job_ids": ["10", "11"],
            "hostname": "h",
            "remote_dir": "/r",
            "username": "",
            "is_sharded": True,
        }
        content = SlurmExecutor().logs("/r", shard_idx=9)
        assert "out of range" in content

    @patch("nemo_evaluator.executors.slurm_executor._read_meta")
    @patch("nemo_evaluator.executors.ssh.ssh_run")
    def test_logs_custom_tail(self, mock_ssh, mock_meta):
        from nemo_evaluator.executors.slurm_executor import SlurmExecutor

        mock_meta.return_value = {
            "job_id": "10",
            "job_ids": ["10", "11"],
            "hostname": "h",
            "remote_dir": "/r",
            "username": "",
            "is_sharded": True,
        }
        mock_ssh.return_value = "lines"

        SlurmExecutor().logs("/r", tail=100)
        call_cmd = mock_ssh.call_args[0][1]
        assert "tail -n 100" in call_cmd


# ---------------------------------------------------------------------------
# Sharded resume
# ---------------------------------------------------------------------------


class TestShardedResume:
    def _make_run_meta(self, job_ids):
        from nemo_evaluator.run_store import RunMeta

        return RunMeta(
            run_id="test-run",
            executor="slurm",
            output_dir="/r",
            started_at="2026-01-01",
            details={
                "job_id": job_ids[0],
                "job_ids": job_ids,
                "hostname": "h",
                "remote_dir": "/r",
                "username": "",
            },
        )

    @patch("nemo_evaluator.executors.slurm_executor._resolve_shard_latest_ids")
    @patch("nemo_evaluator.executors.ssh.batch_check_job_status")
    @patch("nemo_evaluator.executors.ssh.ssh_run")
    def test_resume_only_failed_shards(self, mock_ssh, mock_batch, mock_latest):
        from nemo_evaluator.executors.slurm_executor import SlurmExecutor

        job_ids = ["10", "11", "12"]
        mock_latest.return_value = job_ids
        mock_batch.return_value = {
            "10": {"job_id": "10", "state": "COMPLETED"},
            "11": {"job_id": "11", "state": "FAILED"},
            "12": {"job_id": "12", "state": "TIMEOUT"},
        }
        mock_ssh.return_value = "Submitted batch job 200"

        rm = self._make_run_meta(job_ids)
        with patch.object(rm, "update_details"):
            SlurmExecutor().resume_run(rm)

        sbatch_calls = [c for c in mock_ssh.call_args_list if "sbatch" in c[0][1]]
        assert len(sbatch_calls) == 2
        assert "shard_1" in sbatch_calls[0][0][1]
        assert "shard_2" in sbatch_calls[1][0][1]

    @patch("nemo_evaluator.executors.slurm_executor._resolve_shard_latest_ids")
    @patch("nemo_evaluator.executors.ssh.batch_check_job_status")
    @patch("nemo_evaluator.executors.ssh.ssh_run")
    def test_resume_specific_shard(self, mock_ssh, mock_batch, mock_latest):
        from nemo_evaluator.executors.slurm_executor import SlurmExecutor

        job_ids = ["10", "11"]
        mock_latest.return_value = job_ids
        mock_ssh.return_value = "Submitted batch job 300"

        rm = self._make_run_meta(job_ids)
        with patch.object(rm, "update_details"):
            SlurmExecutor().resume_run(rm, shard_idx=0)

        sbatch_calls = [c for c in mock_ssh.call_args_list if "sbatch" in c[0][1]]
        assert len(sbatch_calls) == 1
        assert "shard_0" in sbatch_calls[0][0][1]

    @patch("nemo_evaluator.executors.slurm_executor._resolve_shard_latest_ids")
    @patch("nemo_evaluator.executors.ssh.batch_check_job_status")
    @patch("nemo_evaluator.executors.ssh.ssh_run")
    def test_resume_all_completed_no_op(self, mock_ssh, mock_batch, mock_latest):
        from nemo_evaluator.executors.slurm_executor import SlurmExecutor

        job_ids = ["10", "11"]
        mock_latest.return_value = job_ids
        mock_batch.return_value = {
            "10": {"job_id": "10", "state": "COMPLETED"},
            "11": {"job_id": "11", "state": "COMPLETED"},
        }

        rm = self._make_run_meta(job_ids)
        SlurmExecutor().resume_run(rm)

        sbatch_calls = [c for c in mock_ssh.call_args_list if "sbatch" in c[0][1]]
        assert len(sbatch_calls) == 0


# ---------------------------------------------------------------------------
# Parent-level meta & resolve
# ---------------------------------------------------------------------------


class TestParentLevelMeta:
    def test_resolve_job_finds_sharded_meta(self, tmp_path):
        """Parent-level slurm_job.json allows _read_meta to find sharded runs."""
        from nemo_evaluator.executors.slurm_executor import _META_FILE, resolve_job

        meta = {
            "job_id": "10",
            "job_ids": ["10", "11"],
            "hostname": "h",
            "remote_dir": "/remote/parent",
            "is_sharded": True,
        }
        store = tmp_path / "jobs" / "sharded_10"
        store.mkdir(parents=True)
        (store / _META_FILE).write_text(json.dumps(meta))

        with patch("nemo_evaluator.executors.slurm_executor._jobs_store", return_value=tmp_path / "jobs"):
            result = resolve_job(output_dir="/remote/parent")

        assert result is not None
        assert result["job_ids"] == ["10", "11"]
        assert result["is_sharded"] is True


class TestResolveRunJobIds:
    def test_resolve_by_shard_job_id(self, tmp_path):
        """resolve_run finds a run when given a non-primary shard job_id."""
        from nemo_evaluator.run_store import RunMeta, resolve_run, _RUN_META

        run_id = "test_20260326_000000_abc"
        rm = RunMeta(
            run_id=run_id,
            executor="slurm",
            output_dir="/remote",
            started_at="2026-03-26",
            details={
                "job_id": "100",
                "job_ids": ["100", "101", "102"],
                "hostname": "h",
            },
        )
        store_dir = tmp_path / "runs" / run_id
        store_dir.mkdir(parents=True)
        (store_dir / _RUN_META).write_text(json.dumps(rm.__dict__))

        with patch("nemo_evaluator.run_store._runs_store", return_value=tmp_path / "runs"):
            result = resolve_run(job_id="101")

        assert result is not None
        assert result.run_id == run_id

    def test_resolve_primary_shard_still_works(self, tmp_path):
        from nemo_evaluator.run_store import RunMeta, resolve_run, _RUN_META

        run_id = "test_run"
        rm = RunMeta(
            run_id=run_id,
            executor="slurm",
            output_dir="/remote",
            started_at="2026-03-26",
            details={"job_id": "100", "job_ids": ["100", "101"], "hostname": "h"},
        )
        store_dir = tmp_path / "runs" / run_id
        store_dir.mkdir(parents=True)
        (store_dir / _RUN_META).write_text(json.dumps(rm.__dict__))

        with patch("nemo_evaluator.run_store._runs_store", return_value=tmp_path / "runs"):
            result = resolve_run(job_id="100")

        assert result is not None


# ---------------------------------------------------------------------------
# Batch check job status
# ---------------------------------------------------------------------------


class TestBatchCheckJobStatus:
    @patch("nemo_evaluator.executors.ssh._ssh")
    def test_squeue_batch(self, mock_ssh):
        from nemo_evaluator.executors.ssh import batch_check_job_status

        mock_ssh.return_value = "10|eval|RUNNING|1:00:00|node1\n11|eval|PENDING||"

        result = batch_check_job_status("h", ["10", "11"])
        assert result["10"]["state"] == "RUNNING"
        assert result["11"]["state"] == "PENDING"

    @patch("nemo_evaluator.executors.ssh._ssh")
    def test_sacct_fallback(self, mock_ssh):
        from nemo_evaluator.executors.ssh import batch_check_job_status

        def side_effect(target, cmd, timeout=15.0):
            if "squeue" in cmd:
                return ""
            if "sacct" in cmd:
                return "10|COMPLETED|0:0\n11|FAILED|1:0"
            return ""

        mock_ssh.side_effect = side_effect
        result = batch_check_job_status("h", ["10", "11"])
        assert result["10"]["state"] == "COMPLETED"
        assert result["11"]["state"] == "FAILED"

    @patch("nemo_evaluator.executors.ssh._ssh")
    def test_unknown_fallback(self, mock_ssh):
        from nemo_evaluator.executors.ssh import SSHError, batch_check_job_status

        mock_ssh.side_effect = SSHError("nope")
        result = batch_check_job_status("h", ["10"])
        assert result["10"]["state"] == "UNKNOWN"

    def test_empty_list(self):
        from nemo_evaluator.executors.ssh import batch_check_job_status

        assert batch_check_job_status("h", []) == {}


# ---------------------------------------------------------------------------
# _resolve_latest_job_id / _resolve_shard_latest_ids
# ---------------------------------------------------------------------------


class TestResolveLatestJobId:
    @patch("nemo_evaluator.executors.ssh.ssh_run")
    def test_follows_chain(self, mock_ssh):
        from nemo_evaluator.executors.slurm_executor import _resolve_latest_job_id

        mock_ssh.return_value = "999\n"
        result = _resolve_latest_job_id("h", "/run", "100", "user")
        assert result == "999"

    @patch("nemo_evaluator.executors.ssh.ssh_run")
    def test_empty_chain_returns_fallback(self, mock_ssh):
        from nemo_evaluator.executors.slurm_executor import _resolve_latest_job_id

        mock_ssh.return_value = ""
        assert _resolve_latest_job_id("h", "/run", "100") == "100"

    @patch("nemo_evaluator.executors.ssh.ssh_run", side_effect=Exception("SSH down"))
    def test_ssh_error_returns_fallback(self, mock_ssh):
        from nemo_evaluator.executors.slurm_executor import _resolve_latest_job_id

        assert _resolve_latest_job_id("h", "/run", "100") == "100"

    def test_empty_hostname_returns_fallback(self):
        from nemo_evaluator.executors.slurm_executor import _resolve_latest_job_id

        assert _resolve_latest_job_id("", "/run", "100") == "100"

    def test_empty_remote_dir_returns_fallback(self):
        from nemo_evaluator.executors.slurm_executor import _resolve_latest_job_id

        assert _resolve_latest_job_id("h", "", "100") == "100"


class TestResolveShardLatestIds:
    @patch("nemo_evaluator.executors.ssh.ssh_run")
    def test_batch_resolve(self, mock_ssh):
        from nemo_evaluator.executors.slurm_executor import _resolve_shard_latest_ids

        mock_ssh.return_value = "200\n201\n202\n"
        result = _resolve_shard_latest_ids("h", "/run", ["10", "11", "12"])
        assert result == ["200", "201", "202"]

    @patch("nemo_evaluator.executors.ssh.ssh_run")
    def test_partial_output_returns_fallback(self, mock_ssh):
        from nemo_evaluator.executors.slurm_executor import _resolve_shard_latest_ids

        mock_ssh.return_value = "200\n"
        result = _resolve_shard_latest_ids("h", "/run", ["10", "11", "12"])
        assert result == ["10", "11", "12"]

    @patch("nemo_evaluator.executors.ssh.ssh_run", side_effect=Exception("SSH down"))
    def test_ssh_error_returns_fallback(self, mock_ssh):
        from nemo_evaluator.executors.slurm_executor import _resolve_shard_latest_ids

        result = _resolve_shard_latest_ids("h", "/run", ["10", "11"])
        assert result == ["10", "11"]

    def test_empty_list(self):
        from nemo_evaluator.executors.slurm_executor import _resolve_shard_latest_ids

        assert _resolve_shard_latest_ids("h", "/run", []) == []

    @patch("nemo_evaluator.executors.ssh.ssh_run")
    def test_single_delegates_to_resolve_latest(self, mock_ssh):
        from nemo_evaluator.executors.slurm_executor import _resolve_shard_latest_ids

        mock_ssh.return_value = "999\n"
        result = _resolve_shard_latest_ids("h", "/run", ["10"])
        assert result == ["999"]


# ---------------------------------------------------------------------------
# Resume error handling
# ---------------------------------------------------------------------------


class TestResumePartialFailure:
    """Test that per-shard error handling in resume_run() works correctly."""

    def _make_run_meta(self, job_ids):
        from nemo_evaluator.run_store import RunMeta

        return RunMeta(
            run_id="test-run",
            executor="slurm",
            output_dir="/r",
            started_at="2026-01-01",
            details={
                "job_id": job_ids[0],
                "job_ids": job_ids,
                "hostname": "h",
                "remote_dir": "/r",
                "username": "",
            },
        )

    @patch("nemo_evaluator.executors.slurm_executor._resolve_shard_latest_ids")
    @patch("nemo_evaluator.executors.ssh.batch_check_job_status")
    @patch("nemo_evaluator.executors.ssh.ssh_run")
    def test_one_shard_fails_others_succeed(self, mock_ssh, mock_batch, mock_latest):
        from nemo_evaluator.executors.slurm_executor import SlurmExecutor

        job_ids = ["10", "11", "12"]
        mock_latest.return_value = job_ids
        mock_batch.return_value = {
            "10": {"job_id": "10", "state": "FAILED"},
            "11": {"job_id": "11", "state": "FAILED"},
            "12": {"job_id": "12", "state": "FAILED"},
        }

        call_count = [0]

        def ssh_side_effect(hostname, cmd, **kwargs):
            if "sbatch" in cmd:
                call_count[0] += 1
                if "shard_1" in cmd:
                    raise Exception("Connection reset")
                return f"Submitted batch job {200 + call_count[0]}"
            return ""

        mock_ssh.side_effect = ssh_side_effect

        rm = self._make_run_meta(job_ids)
        with patch.object(rm, "update_details"):
            SlurmExecutor().resume_run(rm)

        sbatch_calls = [c for c in mock_ssh.call_args_list if "sbatch" in c[0][1]]
        assert len(sbatch_calls) == 3


# ---------------------------------------------------------------------------
# Non-sharded backward compat
# ---------------------------------------------------------------------------


class TestNonShardedStop:
    @patch("nemo_evaluator.executors.slurm_executor._read_meta")
    @patch("nemo_evaluator.executors.ssh.cancel_job")
    def test_stop_single_job(self, mock_cancel, mock_meta):
        from nemo_evaluator.executors.slurm_executor import SlurmExecutor

        mock_meta.return_value = {"job_id": "100", "hostname": "h", "username": ""}
        assert SlurmExecutor().stop("/out") is True
        mock_cancel.assert_called_once_with(hostname="h", job_id="100", username=None)


class TestNonShardedLogs:
    @patch("nemo_evaluator.executors.slurm_executor._read_meta")
    @patch("nemo_evaluator.executors.slurm_executor._resolve_latest_job_id")
    @patch("nemo_evaluator.executors.ssh.ssh_run")
    def test_logs_single_job(self, mock_ssh, mock_latest, mock_meta):
        from nemo_evaluator.executors.slurm_executor import SlurmExecutor

        mock_meta.return_value = {
            "job_id": "100",
            "hostname": "h",
            "username": "",
            "remote_dir": "/run",
        }
        mock_latest.return_value = "100"
        mock_ssh.return_value = "log output here"

        content = SlurmExecutor().logs("/run")
        assert content == "log output here"
        call_cmd = mock_ssh.call_args[0][1]
        assert "slurm-100.log" in call_cmd

    @patch("nemo_evaluator.executors.slurm_executor._read_meta")
    @patch("nemo_evaluator.executors.slurm_executor._resolve_latest_job_id")
    @patch("nemo_evaluator.executors.ssh.ssh_run")
    def test_logs_single_job_with_tail(self, mock_ssh, mock_latest, mock_meta):
        from nemo_evaluator.executors.slurm_executor import SlurmExecutor

        mock_meta.return_value = {
            "job_id": "100",
            "hostname": "h",
            "username": "",
            "remote_dir": "/run",
        }
        mock_latest.return_value = "100"
        mock_ssh.return_value = "last 50 lines"

        content = SlurmExecutor().logs("/run", tail=50)
        assert content == "last 50 lines"
        call_cmd = mock_ssh.call_args[0][1]
        assert "tail -n 50" in call_cmd


class TestNonShardedStatus:
    @patch("nemo_evaluator.executors.slurm_executor._read_meta")
    @patch("nemo_evaluator.executors.ssh._ssh", return_value="200")
    @patch("nemo_evaluator.executors.ssh.check_job_status")
    def test_status_chain_resolves(self, mock_check, mock_ssh_low, mock_meta):
        """Non-sharded status() follows the job chain to get the latest ID."""
        from nemo_evaluator.executors.slurm_executor import SlurmExecutor

        mock_meta.return_value = {
            "job_id": "100",
            "hostname": "h",
            "username": "",
            "remote_dir": "/run",
        }
        mock_check.return_value = {"job_id": "200", "state": "RUNNING"}

        state = SlurmExecutor().status("/run")
        assert state.running is True
        mock_check.assert_called_once_with(hostname="h", job_id="200", username=None)


class TestNonShardedResume:
    @patch("nemo_evaluator.executors.ssh.ssh_run")
    def test_resume_updates_metadata(self, mock_ssh):
        """Non-sharded resume persists the new job ID in RunMeta."""
        from nemo_evaluator.executors.slurm_executor import SlurmExecutor
        from nemo_evaluator.run_store import RunMeta

        mock_ssh.return_value = "Submitted batch job 500"

        rm = RunMeta(
            run_id="test-run",
            executor="slurm",
            output_dir="/run",
            started_at="2026-01-01",
            details={
                "job_id": "100",
                "hostname": "h",
                "remote_dir": "/run",
                "username": "",
            },
        )
        with (
            patch.object(rm, "update_details") as mock_update,
            patch("nemo_evaluator.executors.slurm_executor._jobs_store") as mock_store,
        ):
            mock_store.return_value = MagicMock()
            mock_store.return_value.__truediv__ = MagicMock(return_value=MagicMock())
            SlurmExecutor().resume_run(rm)

        mock_update.assert_called_once()
        call_kwargs = mock_update.call_args[1]
        assert call_kwargs["job_id"] == "500"
        assert call_kwargs["job_ids"] == ["500"]


# ---------------------------------------------------------------------------
# _is_sharded with explicit flag
# ---------------------------------------------------------------------------


class TestIsShardedFlag:
    def test_is_sharded_from_flag(self):
        from nemo_evaluator.executors.slurm_executor import _is_sharded

        meta = {"job_id": "100", "job_ids": ["100"], "is_sharded": True}
        assert _is_sharded(meta) is True

    def test_is_sharded_from_count(self):
        from nemo_evaluator.executors.slurm_executor import _is_sharded

        meta = {"job_id": "100", "job_ids": ["100", "101"]}
        assert _is_sharded(meta) is True

    def test_not_sharded_single_no_flag(self):
        from nemo_evaluator.executors.slurm_executor import _is_sharded

        meta = {"job_id": "100", "job_ids": ["100"]}
        assert _is_sharded(meta) is False


# ---------------------------------------------------------------------------
# _update_aggregate_meta
# ---------------------------------------------------------------------------


class TestUpdateAggregateMeta:
    def test_finds_by_remote_dir(self, tmp_path):
        from nemo_evaluator.executors.slurm_executor import _META_FILE, _update_aggregate_meta

        agg_dir = tmp_path / "sharded_100"
        agg_dir.mkdir()
        (agg_dir / _META_FILE).write_text(
            json.dumps(
                {
                    "job_id": "100",
                    "job_ids": ["100", "101"],
                    "remote_dir": "/lustre/run",
                    "is_sharded": True,
                }
            )
        )

        with patch("nemo_evaluator.executors.slurm_executor._jobs_store", return_value=tmp_path):
            _update_aggregate_meta("/lustre/run", ["200", "201"])

        updated = json.loads((agg_dir / _META_FILE).read_text())
        assert updated["job_ids"] == ["200", "201"]
        assert updated["job_id"] == "100"  # job_id stays stable

    def test_no_match_no_crash(self, tmp_path):
        from nemo_evaluator.executors.slurm_executor import _update_aggregate_meta

        with patch("nemo_evaluator.executors.slurm_executor._jobs_store", return_value=tmp_path):
            _update_aggregate_meta("/nonexistent", ["100"])
