"""Generate a Markdown damage report from a gate run.

Produces a per-benchmark table with scores, deltas, CIs, and statuses,
plus the aggregate verdict and any warnings.  Designed to be attached
to release tickets and waiver requests.

Usage::

    nel gate baseline/ candidate/ --policy policy.yaml --report damage-report.md
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def generate_gate_report(report_dict: dict[str, Any]) -> str:
    """Generate a Markdown damage report from a GateReport dict."""
    lines: list[str] = []
    _w = lines.append

    verdict = report_dict.get("verdict", "ERROR")
    reasons = report_dict.get("verdict_reasons", [])
    warnings = report_dict.get("warnings", [])
    benchmarks = report_dict.get("benchmarks", [])
    missing = report_dict.get("missing", [])

    # ── Header ─────────────────────────────────────────────────────
    _w(f"# Quality Gate Report: {verdict}")
    _w("")
    _w(f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    _w("")

    # ── Verdict ────────────────────────────────────────────────────
    _w("## Verdict")
    _w("")
    _w(f"**{verdict}**")
    _w("")
    if reasons:
        for r in reasons:
            _w(f"- {r}")
        _w("")

    # ── Warnings ───────────────────────────────────────────────────
    if warnings:
        _w("## Warnings")
        _w("")
        for w in warnings:
            _w(f"- {w}")
        _w("")

    # ── Per-benchmark table ────────────────────────────────────────
    if benchmarks:
        _w("## Per-Benchmark Results")
        _w("")
        _w("| Benchmark | Tier | Status | Metric | Baseline | Candidate | Delta (pp) | 95% CI | N |")
        _w("|---|---|---|---|---|---|---|---|---|")

        for b in sorted(benchmarks, key=lambda x: x.get("benchmark", "")):
            name = b.get("benchmark", "?")
            tier = b.get("tier", "?")
            status = b.get("status", "?")
            metric = b.get("metric", "") or ""
            base_s = b.get("baseline_score")
            cand_s = b.get("candidate_score")
            delta = b.get("delta")
            ci_lo = b.get("delta_ci_lower")
            ci_hi = b.get("delta_ci_upper")
            n = b.get("n_paired", 0)

            base_str = f"{base_s:.4f}" if base_s is not None else "—"
            cand_str = f"{cand_s:.4f}" if cand_s is not None else "—"
            delta_str = f"{delta * 100:+.1f}" if delta is not None else "—"
            ci_str = f"[{ci_lo:.4f}, {ci_hi:.4f}]" if ci_lo is not None and ci_hi is not None else "—"
            n_str = f"{n:,}" if n > 0 else "—"

            _w(
                f"| {name} | {tier} | {status} | {metric} | {base_str} | {cand_str} | {delta_str} | {ci_str} | {n_str} |"
            )

        _w("")

    # ── Per-benchmark details ──────────────────────────────────────
    non_pass = [b for b in benchmarks if b.get("status") != "PASS"]
    if non_pass:
        _w("## Details")
        _w("")
        for b in non_pass:
            name = b.get("benchmark", "?")
            status = b.get("status", "?")
            b_reasons = b.get("reasons", [])
            rel_drop = b.get("relative_drop_pct")

            _w(f"### {name} — {status}")
            _w("")
            if b_reasons:
                for r in b_reasons:
                    _w(f"- {r}")
            if rel_drop is not None:
                _w(f"- Relative drop: {rel_drop:+.1f}%")
            _w("")

    # ── Missing benchmarks ─────────────────────────────────────────
    if missing:
        _w("## Missing Benchmarks")
        _w("")
        for m in missing:
            _w(f"- `{m}`")
        _w("")

    # ── Footer ─────────────────────────────────────────────────────
    _w("---")
    _w("*Report generated by NeMo Evaluator `nel gate`*")

    return "\n".join(lines)


def write_gate_markdown(report_dict: dict[str, Any], output_path: str | Path) -> Path:
    """Write a Markdown damage report to disk."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(generate_gate_report(report_dict), encoding="utf-8")
    return path
