# nemo-evaluator with all harnesses
# For: any benchmark scheme. Larger image but zero additional pulls needed.
ARG BASE_IMAGE=nemo-evaluator:latest
FROM ${BASE_IMAGE}

WORKDIR /app

RUN pip install --no-cache-dir ".[all]"

CMD ["nel", "--help"]
