nemotron:
  type: vllm
  model: nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-FP8
  protocol: chat_completions
  port: 5000
  tensor_parallel_size: 4
  data_parallel_size: 2
  image: vllm/vllm-openai:v0.18.0-cu130
  startup_timeout: 1800.0
  setup_commands:
    - 'curl -sSL -o /tmp/super_v3_reasoning_parser.py https://huggingface.co/nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-FP8/resolve/main/super_v3_reasoning_parser.py'
  extra_args:
    - "--async-scheduling"
    - "--dtype=auto"
    - "--kv-cache-dtype=fp8"
    - "--trust-remote-code"
    - "--attention-backend=TRITON_ATTN"
    - "--gpu-memory-utilization=0.9"
    - "--enable-chunked-prefill"
    - "--max-num-seqs=512"
    - "--enable-auto-tool-choice"
    - "--tool-call-parser=qwen3_coder"
    - "--reasoning-parser-plugin=/tmp/super_v3_reasoning_parser.py"
    - "--reasoning-parser=super_v3"
  extra_env:
    VLLM_CACHE_ROOT: /cache/vllm
    VLLM_ALLOW_LONG_MAX_MODEL_LEN: "1"
  container_mounts:
    - /lustre/fsw/portfolios/coreai/users/${USER}/cache/vllm:/cache/vllm
  generation:
    temperature: 1.0
    top_p: 0.95
    max_tokens: 16384
  proxy:
    interceptors:
      - name: turn_counter
        config:
          max_turns: 100
  node_pool: gpu
