# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Static prose for Core Python API reference pages (ported from legacy Sphinx RST).
# Module members below the prose are autogenerated by generate_api_reference_mdx.py.

API_INDEX = """\
The central point of evaluation is `evaluate()` function that takes standarized input and returns \
standarized output. See [Modeling input and output](/references/api/nemo-evaluator/api/api-dataclasses) \
to learn how to instantiate standardized input and consume standardized output. Below is an example \
of how one might configure and run evaluation via Python API:

```python
from nemo_evaluator.core.evaluate import evaluate
from nemo_evaluator.api.api_dataclasses import (
    EvaluationConfig,
    EvaluationTarget,
    ConfigParams,
    ApiEndpoint,
)

# Create evaluation configuration
eval_config = EvaluationConfig(
    type="simple_evals.mmlu_pro",
    output_dir="./results",
    params=ConfigParams(
        limit_samples=100,
        temperature=0.1,
    ),
)

# Create target configuration
target_config = EvaluationTarget(
    api_endpoint=ApiEndpoint(
        url="https://integrate.api.NVIDIA.com/v1/chat/completions",
        model_id="meta/llama-3.2-3b-instruct",
        type="chat",
        api_key_name="MY_API_KEY",  # env var holding the API key
    )
)

# Run evaluation
result = evaluate(eval_config, target_config)
```
"""

API_DATACLASSES = """\
NeMo Evaluator Core operates on strictly defined input and output which are modelled through \
pydantic dataclasses. Whether you use Python API or CLI, the reference below serves as a map of \
configuration options and output format.
"""

ADAPTERS_OVERVIEW = """\
Interceptors and PostEvalHooks are important part of NeMo Evaluator SDK. They expand functionality \
of each harness, providing a standardized way of enabling features in your evaluation runs. \
Behind each interceptor and post-eval-hook stands a specific class that implements its logic. \
However, these classes are referenced only to provide their configuration options which are reflected \
in `Params` of each class and to point from which classes one should inherit.

From the usage perspective, one should always use configuration classes (see \
[Configuration](/references/api/nemo-evaluator/adapters/adapter-config)) to add them to evaluations. \
No interceptor should be directly instantiated.

Interceptors are defined in a chain. They go under `target.api_endpoint.adapter_config` and can be \
defined as follow:

```python
adapter_config = AdapterConfig(
    interceptors=[
        InterceptorConfig(
            name="system_message",
            enabled=True,
            config={"system_message": "You are a helpful assistant."},
        ),
        InterceptorConfig(name="request_logging", enabled=True),
        InterceptorConfig(
            name="caching",
            enabled=True,
            config={"cache_dir": "./cache", "reuse_cached_responses": True},
        ),
        InterceptorConfig(name="reasoning", enabled=True),
        InterceptorConfig(name="endpoint"),
    ]
)
```
"""

INTERCEPTORS_INDEX = """\
Reference for interceptor implementation classes. For usage and configuration, start with the \
[Adapters overview](/references/api/nemo-evaluator/adapters/adapters) and the \
[Configuration](/references/api/nemo-evaluator/adapters/adapter-config) classes — interceptors \
are enabled through `InterceptorConfig` entries in `AdapterConfig`, not by instantiating the \
classes below directly.

Each class documents its `Params` fields and the request/response hooks it implements.
"""

SANDBOX_INDEX = """\
Sandbox implementations used by evaluation harnesses that need isolated container environments \
for command execution, file transfer, and agent hosting.

This module is designed to keep dependencies **optional**:

- The ECS Fargate implementation only imports AWS SDKs (`boto3`/`botocore`) when actually used.
- Transport is SSH-based; no AWS CLI or session-manager-plugin required on the host.

## Sandbox Protocol

All sandbox backends implement the `Sandbox` protocol, so harnesses can be written \
backend-agnostically:

- `start()` / `stop()` — lifecycle
- `exec(command)` — run a shell command
- `upload(local_path, remote_path)` / `download(remote_path, local_path)` — file transfer
- `is_running` — health check
- Context manager (`with sandbox: ...`) for automatic cleanup

## Usage (ECS Fargate — exec-server mode)

For harnesses that drive execution from the orchestrator (e.g. terminal-bench):

```python
from nemo_evaluator.sandbox import EcsFargateConfig, EcsFargateSandbox, SshSidecarConfig

cfg = EcsFargateConfig(
    region="us-west-2",
    cluster="my-ecs-cluster",
    subnets=["subnet-abc"],
    security_groups=["sg-xyz"],
    image_template="123456789.dkr.ecr.us-west-2.amazonaws.com/my-repo:{task_id}",
    s3_bucket="my-staging-bucket",
    ssh_sidecar=SshSidecarConfig(
        public_key_secret_arn="arn:aws:secretsmanager:...:my-pubkey",
        private_key_secret_arn="arn:aws:secretsmanager:...:my-privkey",
        exec_server_port=19542,
    ),
)

with EcsFargateSandbox(cfg, task_id="task-001", run_id="run-001") as sandbox:
    sandbox.start()
    result = sandbox.exec("echo hello")
    print(result.stdout)
```

## Usage (ECS Fargate — agent-server mode)

For harnesses that host an agent inside the container (e.g. openhands), omit `exec_server_port` \
and pass `OutsideEndpoint` to `start()`:

```python
from nemo_evaluator.sandbox import OutsideEndpoint

cfg = EcsFargateConfig(
    ...
    ssh_sidecar=SshSidecarConfig(
        public_key_secret_arn="arn:aws:secretsmanager:...:my-pubkey",
        private_key_secret_arn="arn:aws:secretsmanager:...:my-privkey",
    ),
)

model_ep = OutsideEndpoint(url="http://localhost:8080", env_var="MODEL_BASE_URL")

with EcsFargateSandbox(cfg, task_id="task-001", run_id="run-001") as sandbox:
    sandbox.start(outside_endpoints=[model_ep])
    # The agent inside the container can now reach the model via the reverse tunnel.
    # The orchestrator can reach the agent's API via sandbox.local_port.
```

## Prerequisites / Notes

- SSH keys must be **pre-provisioned** in AWS Secrets Manager.
- If you use S3-based file staging (large uploads / downloads), configure `s3_bucket`.
- Docker image building via AWS CodeBuild is available through `ImageBuilder`.
"""
