# Chat model evaluation configuration (chat endpoint)
evaluation:
  nemo_evaluator_config:
    config:
      params:
        request_timeout: 3600
        parallelism: 64
        temperature: 0.0 # Deterministic for reproducibility
        max_new_tokens: 2048
