# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: "Release NeMo-Eval (scheduled)"

# NOTE(if-changed): check the `release.yaml` workflow for sync
# between the paramters of this job (scheduled) and that one (manual).
on:
  schedule:
    # Mon-Thu
    - cron: "0 1 * * 1-4"
  # NOTE(agronskiy): does not hurt but this to be removed once testing on main done.
  workflow_dispatch:

permissions:
  contents: write # To read repository content
  pull-requests: write # To create PRs

jobs:
  # NOTE(if-changed): check the `release.yaml` workflow for sync
  # between the paramters of this job (scheduled) and that one (manual).
  release-scheduled-evaluator:
    uses: NVIDIA-NeMo/FW-CI-templates/.github/workflows/_release_library.yml@v0.62.0
    with:
      release-ref: ${{ github.sha }}
      python-package: nemo_evaluator
      library-name: NeMo Evaluator
      dry-run: false
      version-bump-branch: main
      create-gh-release: true
      gh-release-tag-prefix: nemo-evaluator-
      packaging: uv
      skip-test-wheel: true
      app-id: ${{ vars.BOT_ID }}
      has-src-dir: true
      root-dir: packages/nemo-evaluator
    secrets:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      SLACK_WEBHOOK_ADMIN: ${{ secrets.SLACK_WEBHOOK_ADMIN }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_RELEASE_ENDPOINT }}
      PAT: ${{ secrets.PAT }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_PWD: ${{ secrets.SSH_PWD }}
      BOT_KEY: ${{ secrets.BOT_KEY }}

  # NOTE(if-changed): check the `release.yaml` workflow for sync
  # between the paramters of this job (scheduled) and that one (manual).
  release-scheduled-evaluator-launcher:
    # Runs after another release to avoid effects of concurrent pushes to `main`.
    needs: release-scheduled-evaluator
    uses: NVIDIA-NeMo/FW-CI-templates/.github/workflows/_release_library.yml@v0.62.0
    with:
      release-ref: ${{ github.sha }}
      python-package: nemo_evaluator_launcher
      library-name: NeMo Evaluator Launcher
      dry-run: false
      version-bump-branch: main
      create-gh-release: true
      gh-release-tag-prefix: nemo-evaluator-launcher-
      packaging: uv
      skip-test-wheel: true
      app-id: ${{ vars.BOT_ID }}
      has-src-dir: true
      root-dir: packages/nemo-evaluator-launcher
    secrets:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      SLACK_WEBHOOK_ADMIN: ${{ secrets.SLACK_WEBHOOK_ADMIN }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_RELEASE_ENDPOINT }}
      PAT: ${{ secrets.PAT }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_PWD: ${{ secrets.SSH_PWD }}
      BOT_KEY: ${{ secrets.BOT_KEY }}
